title:            MLVU
description:      The BSc course Machine Learning at the Vrije Universiteit Amsterdam

defaults:
  -
    scope:
        path: ""
    values:
        article: true
        maps: false
        front: false